version: '3'
services:

  #PHP Service
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: laravel
    restart: unless-stopped
    working_dir: /var/www
    volumes: 
      - ${APP_CODE_PATH_HOST}:/var/www
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: laravel-server
    restart: unless-stopped
    ports:
      - "8222:80"
      - "445:443"
    volumes: 
      - ${APP_CODE_PATH_HOST}:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
# In MAC OS, uncomment a following line
#    platform: linux/x86_64
#mac m1
    #image: mariadb:10.5.8
    image: mysql:5.7
    container_name: laravel-db
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes: 
      - dbdata:/var/lib/mysql
      #- ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes: 
  dbdata:
    driver: local
    
